version: '2'
services:
  loopback-mongo-sandbox:
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      # User-relative path
      - ~/dev/loopback-mongo-sandbox:/apps/loopback-mongo-sandbox
    depends_on:
     - mongo
  mongo:
    image: mongo
    ports:
      - "3001:27017"
